### ISSUE TITLE
pass --xingMin argument to bxlumi related chart

### ISSUE THREAD

**Issue by xiezhen** [cms-bril/brilview#3]
Hello,
    bxlumi related brilcalc command  ```brilcalc lumi --xing``` takes the following special arguments :

'''
--xingId BXID : select bunch by id. Input can be a single number, a comma separated list in file or string format. e.g. --xingId "1,2,3"

--xingTr BXTHRESHOLD : select bunch with luminosity above the specified fraction of the max bx lumi. Input is a float number between 0 and 1. e.g. 0.85.

--xingMin XINGMIN : select bunch with luminosity greater than the specified value. Note: any scaling effect from -n or -u options are already taken into account. The specified min value cut is applied to the final number.
'''

Could you please evaluate the changes, in backend and in frontend, needed to pass through these filters to the per bunch lumi charts of brilview? With priority in --xingMin. 

thanks,
Zhen

**Comment by DiamantisPa** [comment]
- We need 3 more forms in the UI for the BXID, BXTHRESHOLD and XINGMIN values (bxlumi-inspector/form/.html)
- Pass values to the angular service (bxlumi-inspector/form/.ts)
- Send values to backend (bxlumi-inspector/data.service.ts)
- Modify get_brilcalc_bxlumi() in handler/cmmdhandler.py to handle the new values

**Comment by xiezhen** [comment]
fixed with version 1.5.3
