### ISSUE TITLE
pass --datatag argument to totlumi plot

### ISSUE THREAD

**Issue by xiezhen** [cms-bril/brilview#5]
pass --datatag argument from brilcalc backend to brilview in the tot lumi chart

**Comment by DiamantisPa** [comment]
- New UI for totlumi page with the functionality of selecting the required datatag
- New API endpoint for retrieving all possible datatags for DB
- New services for communication between client and server
- Updated backend cmmd handler for managing the --datatag argument
- Added functionality for parsing the datatag from the backend response
